services:
  bkg:
    container_name: bkg
    build: .
    volumes:
      - .:/app
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - GITHUB_OWNER=$GITHUB_OWNER
      - GITHUB_REPO=$GITHUB_REPO
      - GITHUB_BRANCH=$GITHUB_BRANCH
