name: demanded

on:
    push:
        branches:
            - master

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    update:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Update database
              run: bash update.sh 1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Commit and push
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: 'update database'
