name: manual

on:
  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    # GitHub Actions run without a TTY device. This is a workaround to get one,
    # based on https://github.com/actions/runner/issues/241#issuecomment-2019042651
    shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"

      - name: Update database
        id: update
        run: bash update.sh 1 ; echo "updated=$?" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BKG_VERSION: ${{ steps.date.outputs.date }}

      - name: Commit update
        id: commit
        if: ${{ steps.update.outputs.updated == 'true' }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "update database"
          pull: "--autostash"

      - name: Create release
        if: ${{ steps.update.outputs.updated == 'true' && steps.commit.outputs.committed == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "index.sql.zst,index.sql.d/*"
          bodyFile: "CHANGELOG.md"
          tag: "${{ steps.date.outputs.date }}"
          commit: "${{ steps.commit.outputs.commit_long_sha }}"
          allowUpdates: true

