name: manual

on:
  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"

      - name: Update database
        run: bash update.sh 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BKG_VERSION: ${{ steps.date.outputs.date }}

      - name: Commit update
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "update database"
          pull: "--autostash"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "index.sql.zst,index.sql.d/*"
          bodyFile: "CHANGELOG.md"
          tag: "${{ steps.date.outputs.date }}"
          commit: "${{ steps.commit.outputs.commit_long_sha }}"
          allowUpdates: true

