name: refesh

on:
    workflow_run:
      workflows: [demanded, scheduled]
      types:
        - completed

jobs:
    refresh:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Refresh endpoint
              run: bash refre.sh
              env:
                  GITHUB_OWNER: ${{ github.repository_owner }}
                  GITHUB_REPO: ${{ github.event.repository.name }}
                  GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}

            - name: Commit and push
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: 'refresh endpoint'
