name: refresh

on:
  workflow_run:
    workflows: ["update"]
    types:
      - completed

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    # GitHub Actions run without a TTY device. This is a workaround to get one,
    # based on https://github.com/actions/runner/issues/241#issuecomment-2019042651
    shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'

jobs:
  refresh:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dry run
        id: changed
        run: bash src/test/refre.sh ; echo "changed=$?" >> "$GITHUB_OUTPUT"

      - name: Update endpoint
        if: ${{ steps.changed.outputs.changed == '0' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.json'
          message: "refresh endpoint"
          pull: "--autostash -Xours"
