name: refresh

on:
  push:
    branches:
      - master

  workflow_run:
    workflows: ["update"]
    types:
      - completed

  workflow_dispatch:

defaults:
  run:
    # GitHub Actions run without a TTY device. This is a workaround to get one,
    # based on https://github.com/actions/runner/issues/241#issuecomment-2019042651
    shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'

jobs:
  refresh:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Refresh endpoint
        id: changed
        run: bash refre.sh ; echo "changed=$?" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
          GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}

      - name: Commit refresh
        if: ${{ steps.changed.outputs.changed == '0' }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "refresh endpoint"
          pull: "--autostash --strategy-option=ours"
