name: update

on:
  schedule:
    - cron: "*/10 * * * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    # GitHub Actions run without a TTY device. This is a workaround to get one,
    # based on https://github.com/actions/runner/issues/241#issuecomment-2019042651
    shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest data
        run: cd src ; source bkg.sh && get_db ; cd ..

      - name: Fetch all data
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: "*.zst"
          tarBall: false
          zipBall: false

      - name: Dry run
        id: update
        run: bash src/test/update.sh ; echo "updated=$?" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
          GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}

      - name: Save state
        id: commit
        if: ${{ steps.update.outputs.updated == '0' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: "-- *.txt README.md"
          message: "hydration"

      - name: Get date
        id: date
        run: echo "date=$(grep -oP 'BKG_BATCH_FIRST_STARTED=\K.*' src/env.env | sed 's/-/./g')" >> "$GITHUB_OUTPUT"

      - name: Save database
        if: ${{ steps.update.outputs.updated == '0' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zst"
          bodyFile: "CHANGELOG.md"
          tag: "${{ steps.date.outputs.date }}"
          commit: "master"
          allowUpdates: true
