name: update

on:
  workflow_run:
    workflows: ["refresh"]
    types:
      - completed

  workflow_dispatch:

  schedule:
    - cron: '0 */6 * * *'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    # GitHub Actions run without a TTY device. This is a workaround to get one,
    # based on https://github.com/actions/runner/issues/241#issuecomment-2019042651
    shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get date
        id: date
        run: echo "date=$(date -u +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"

      - name: Dry run
        id: update
        run: bash src/test/update.sh 0 ; echo "updated=$?" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
          GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}

      - name: Update environment
        id: commit
        if: ${{ steps.update.outputs.updated == '0' }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "update database"
          pull: "--autostash --strategy-option=ours"

      - name: Save database
        if: ${{ steps.update.outputs.updated == '0' && steps.commit.outputs.committed == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "index.sql.zst,index.sql.d/*"
          bodyFile: "CHANGELOG.md"
          tag: "${{ steps.date.outputs.date }}"
          commit: "${{ steps.commit.outputs.commit_long_sha }}"
          allowUpdates: true
